colang_version: "1.0"

models:
  - type: main
    engine: ollama
    model: llama3.2:latest

core:
  embedding_search_provider:
    name: default
    parameters:
      embedding_engine: FastEmbed
      embedding_model: all-MiniLM-L6-v2